project:
  type: website
  output-dir: _site

website:
  title: "George Mwangi"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "Github"
        href: https://github.com/mwangi-george
        icon: fa-github
      - text: "LinkedIn"
        href: https://www.linkedin.com/in/georgemwangikenya/
        icon: fa-twitter

format:
  html:
    theme: cosmo
    toc: true

output:
  html_document:
  